apiVersion: v1
kind: Pod
metadata:
  name: resonite-pod
spec:
  containers:
    - name: resonite-headless
      image: shadowpanther/resonite-headless
      env:
        - name: STEAMBETA
          valueFrom:
            configMapKeyRef:
              name: resonite-config
              key: STEAMBETA
        - name: STEAMBETAPASSWORD
          valueFrom:
            configMapKeyRef:
              name: resonite-config
              key: STEAMBETAPASSWORD
        - name: STEAMLOGIN
          valueFrom:
            configMapKeyRef:
              name: resonite-config
              key: STEAMLOGIN
      volumeMounts:
        - name: config-vol
          mountPath: /Config
          readOnly: true
        - name: logs-vol
          mountPath: /Logs
  volumes:
    - name: config-vol
      configMap:
        name: resonite-config
        items:
          - key: Config.json
            path: Config.json
    - name: logs-vol
      emptyDir: {}
